version: '3.8'
services:
  server:
    build: ./server_side
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    volumes:
      - ./server_side:/app
      - ./requirements.txt:/app/requirements.txt
    depends_on:
      - agent
  agent:
    build: ./agent
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    volumes:
      - ./agent:/app
      - ./requirements.txt:/app/requirements.txt
    depends_on:
      - server
  client:
    build: ./client_side
    ports:
      - "7860:7860"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    volumes:
      - ./client_side:/app
      - ./requirements.txt:/app/requirements.txt
    depends_on:
      - server
      - agent
